version: '3'
services:

  cnc:
    build: ./cnc
    networks:
      my_network:
        ipv4_address: 192.168.1.3
    expose:
      - 23
      - 101

  bot:
    depends_on:
      - cnc
    build: ./bot
    networks:
      my_network:
        ipv4_address: 192.168.1.2

  victim:
    build: ./victim
    tty: true
    networks:
      my_network:
        ipv4_address: 192.168.1.4
    expose:
      - 23

  admin:
    build: ./admin
    networks:
      my_network:
        ipv4_address: 192.168.1.5

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

